get_blog:
    pattern: /
    defaults: { _controller: JustOnePage\Blog\BlogController::get}
    requirements:
        _method: GET

get_post:
    pattern: /post/{slug}
    defaults: { _controller: JustOnePage\Blog\PostController::get }
    requirements:
        _method: GET

post_post:
    pattern: /post/
    defaults: { _controller: JustOnePage\Blog\PostController::post}
    requirements:
        _method: POST

put_post:
    pattern: /post/{slug}
    defaults: { _controller: JustOnePage\Blog\PostController::put}
    requirements:
        _method: POST

delete_post:
    pattern: /post/{slug}/delete
    defaults: { _controller: JustOnePage\Blog\PostController::delete}
    requirements:
        _method: POST