services:
    config_locator:
        class: Symfony\Component\Config\FileLocator
        factory_class: JustOnePage\Kernel\ConfigLocatorFactory
        factory_method: get

    service_container_factory:
        class: JustOnePage\Kernel\ServiceContainerFactory
        arguments:
            - "@config_locator"

    service_container:
        class: Symfony\Component\DependencyInjection\ContainerInterface
        factory_service: service_container_factory
        factory_method: get

    request:
        class: Symfony\Component\HttpFoundation\Request
        factory_class: JustOnePage\Kernel\RequestFactory
        factory_method: get

    router_factory:
        class: JustOnePage\Kernel\RouterFactory
        arguments:
            - @config_locator
            - @request

    router:
        class: Symfony\Component\Routing\RouterInterface
        factory_service: router_factory
        factory_method: get

    controller_invoker:
        class: JustOnePage\Kernel\ControllerInvoker
        arguments:
            - "@router"
            - "@request"