services:
    config_locator:
        class: Symfony\Component\Config\FileLocator
        factory_class: JustOneBlog\ConfigLocatorFactory
        factory_method: get

    service_container_factory:
        class: JustOneBlog\ServiceContainerFactory
        arguments:
            - "@config_locator"

    service_container:
        class: Symfony\Component\DependencyInjection\ContainerInterface
        factory_service: service_container_factory
        factory_method: get

    request:
        class: Symfony\Component\HttpFoundation\Request
        factory_class: JustOneBlog\RequestFactory
        factory_method: get

    router_factory:
        class: JustOneBlog\RouterFactory
        arguments:
            - @config_locator
            - @request

    router:
        class: Symfony\Component\Routing\RouterInterface
        factory_service: router_factory
        factory_method: get

    application:
        class: JustOneBlog\App
        arguments:
            - "@service_container"
            - "@router"
            - "@request"

    controller_invoker:
        class: JustOneBlog\Controller\Invoker
        arguments:
            - "@router"
            - "@request"